---
name: vps

releases:
- name: postgres
  url: file://./postgres-release-8.tgz
- name: vps
  url: file://./vps-1.tgz
- name: bosh-softlayer-cpi
  url: file://./bosh-softlayer-cpi-2.3.22.tgz
  
resource_pools:
- name: vms
  network: default
  stemcell:
    url: file://./light-bosh-stemcell-3169.1-softlayer-esxi-ubuntu-trusty-go_agent.tgz
  cloud_properties:
    Domain: softlayer.com
    VmNamePrefix: vps-test
    EphemeralDiskSize: 100
    StartCpus: 4
    MaxMemory: 8192
    Datacenter:
       Name: lon02
    HourlyBillingFlag: true
    LocalDiskFlag: true
    PrimaryNetworkComponent:
       NetworkVlan:
          Id: 524956
    PrimaryBackendNetworkComponent:
       NetworkVlan:
          Id: 524954
    NetworkComponents:
    - MaxSpeed: 1000
disk_pools:
- name: disks
  disk_size: 40_000


networks:
- name: default
  type: dynamic
  dns: 
  - 8.8.8.8

jobs:
- name: vps
  instances: 1

  templates:
  - {name: postgres-9.4, release: postgres}
  - {name: vps, release: vps}

  resource_pool: vms

  networks:
  - name: default

  properties:
    postgres: &20585760
      user: postgres
      password: postgres
      host: 127.0.0.1
      database: bosh
      adapter: postgres
    vps:
      host: 127.0.0.1
      port: 8889
      log_level: debug
      sql:
        db_username: postgres
        db_password: postgres
        db_host: 127.0.0.1
        db_port: 5432
        db_schema: bosh
        db_driver: postgres
        
    softlayer: &softlayer
      username: <username>   <Please replace it with your username>
      apiKey: <apikey>   <Please replace it with your apikey>

    agent: {mbus: "nats://nats:nats@127.0.0.1:4222"}

    ntp: &ntp []
 
cloud_provider:
  template: {name: softlayer_cpi, release: bosh-softlayer-cpi}

  # Tells bosh-init how to contact remote agent
  mbus: https://admin:admin@vps-test.softlayer.com:6868   <Please be consistent with the VmNamePrefix in hostname>

  properties:
    softlayer: *softlayer

    # Tells CPI how agent should listen for bosh-init requests
    agent: {mbus: "https://admin:admin@vps-test.softlayer.com:6868"}   <Please be consistent with the VmNamePrefix in hostname>

    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}

    ntp: *ntp
